dist: xenial

branches:
  only:
    - master

node_js:
  - 14

jdk:
  - openjdk11

language: java

install: true

before_script:
  - source configure.sh
script: ./gradlew build --info

after_success:
  - bash <(curl -s https://codecov.io/bash)
