dist: focal

branches:
  only:
    - master

jdk:
  - openjdk11
env:
  - NODE_VERSION=14.14.0

install:
  - nvm install $NODE_VERSION

language: java

before_script:
  - source configure.sh
  - npm --version
  - node --version
  - java -version

script:
  - nvm use $NODE_VERSION
  - ./gradlew build --info

after_success:
  - bash <(curl -s https://codecov.io/bash)
