info:
  name: demo

spring:
  jpa:
    hibernate.ddl-auto: none

  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/.h2/demo
    username: sa
    password: sa


liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml