spring:
  application:
    name: demo

  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true

  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/.h2/demo
    username: sa
    password: sa
  jmx:
    enabled: true

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain

management:
  context-path: /management

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml

info:
  name: ${spring.application.name}
  version: '@version@'

security:
  user:
    name: user
    password: password
logging:
  level:
    org:
      hibernate:
        engine: info #info to show session times
        type: trace #trace to show binding parameters
        SQL: debug #debug to show generated sql
        stat: debug #debug to show hql query times
