version: "3"

services:
  sonarqube:
    image: sonarqube:7.0-alpine
    restart: always
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - c:\env\sonarqube_conf:/opt/sonarqube/conf
      - c:\env\sonarqube_data:/opt/sonarqube/data
      - c:\env\sonarqube_extensions:/opt/sonarqube/extensions
      - c:\env\sonarqube_bundled:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    restart: always
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
#    volumes:
#      - /c/data/sonarqube_postgresql:/var/lib/postgresql
#      - /c/data/sonarqube_postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
